### ISSUE TITLE
[BUG] Error entering the server

### ISSUE THREAD

**Issue by Richards0nd** [TigoDevelopment/TigoAntiCheat#36]
**Describe the bug**
The error is the following, whenever I start the server it gives these errors:
```
[TigoAntiCheat][ERROR] File lynx_inject.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File vehicle.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File response.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File godmode.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File disabledkeys.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File fake_events.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File main.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File functions.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File config.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File tokenizer.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File visible.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File weapons.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File objects.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File common.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
[TigoAntiCheat][ERROR] File fxmanifest.temp can't be saved in @/home/Tomorrow-SVTESTE/resources//[ESSENTIAL]/neweden_garage_handcuff
```
It is not only this error, the name of the script is always random, there were times when it was the mechanic, ambulance script ... and so on ....

**To Reproduce**
Just start the server ...

**Expected behavior**
These errors should not appear when saving the file, or at most, not having the errors, but only information for debugging

**Screenshots**
![image](https://user-images.githubusercontent.com/45667828/80193402-18ebb580-85ef-11ea-9e9a-c9ce0f270f9e.png)

**Comment by ThymonA** [comment]
The fact that the names differ every time has to do with making it more difficult for tools to determine if you have an AntiCheat. That the resource and names are always different, that's right and is a feature.
That the files could not be saved, can have two things to do with it:
- FXServer has no rights to write in that folder (permission problem on your side)
- FXServer generated a path with 2 slashes instead of 1, this has been solved.

**Comment by kakaogo** [comment]
Unfortunately I have a similar problem :(
Although I am using the latest version.

![tigo](https://user-images.githubusercontent.com/37238017/80314066-4ef78800-87ef-11ea-9f3e-7189358039b9.png)

**Comment by kakaogo** [comment]
Unfortunately I have a similar problem :(
Although I am using the latest version.
![tac-orig](https://user-images.githubusercontent.com/37238017/80314523-4a809e80-87f2-11ea-82fc-2574a9e63faf.jpg)

Each folder got 777 chmod and I also tried to run fxserver as root.
I tried one of the following:
path = path: gsub ("resources //", "resources /")
![tac-modded](https://user-images.githubusercontent.com/37238017/80314519-42286380-87f2-11ea-8196-488e30c2affd.png)

But that didn't solve the problem either, and then the path was good.

**Comment by Jabelius** [comment]
Yea that problem still exists. This resource is broken at the moment.
Maybe it only works on windows?

**Comment by Richards0nd** [comment]
> Yea that problem still exists. This resource is broken at the moment.
> Maybe it only works on windows?

Yes!

**Comment by Jabelius** [comment]
This should be fixed as there is many server owners that are using linux.

**Comment by successtheman** [comment]
I can confirm this same issue on Linux artifact 2341, seems to impact only linux as the thread above seems to indicate
